### ISSUE TITLE
Router does not work with latest HyperApp, 0.15.1

### ISSUE THREAD

**Issue by leifoolsen** [hyperapp/router#25]
Hello,
The router, version 0.3.0,  does not work with the latest HyperApp release.

The following code snippet:
```js
  app({
    view: [
      ['/', () => <h1>Hi.</h1>],
      ['*', () => <h1>404</h1>],
    ],
    mixins: [router()]
  });
```
gives this error in my console: "app.js:27 Uncaught TypeError: props.view is not a function at render (app.js:27)"

The function in HyperApp that causes the error: 
```js
  function render() {
    flush(
      (root = patchElement(
        container,
        root,
        node,
        (node = props.view(globalState, globalActions)),
        (skipRender = !skipRender)
      ))
    )
  }
```
If I downgrade to e.g. hyperapp-0.12.0, the router works as expected.

**Comment by Swizz** [comment]
Due to recent API changes Mixins are not part of Hyperapp anymore. 

See #23
Duplicates of #24

**Comment by leifoolsen** [comment]
@Swizz, thanks for clarification.
I'm do not have much experience with HyperApp, so just copy/pasted code from readme.md. The best thing to do right now is to downgrade HyperApp, I guess?

**Comment by zaceno** [comment]
@leifoolsen Yes for now that's the only way to use the router. But you'll probably end up refactoring a bit when the router works with hyperapp >= 0.15.1. So, depending on how you feel about that, it might be worth waiting too.

**Comment by leifoolsen** [comment]
@zaceno, thanks for reply.
Maybe it's best to wait. I have a webpack boilerplate,https://github.com/leifoolsen/webpack2-boilerplate, (Hyperapp, CSSModules, Node Express, HMR, etc) up and running without routing, so I can experiment with other aspects regarding HyperApp.

**Comment by JorgeBucaran** [comment]
@leifoolsen I just published 0.4.1; it works with hyperapp@0.18.0. Docs are on the README. 👋
